name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install dependencies
      run: ./composer.phar install --prefer-dist --no-progress

    - name: Validate composer.json and composer.lock
      run: ./composer.phar validate --strict

    - name: Run test suite
      run: ./vendor/bin/phpunit test/
